### ISSUE TITLE
I/O of RoBERTa-For-QA component

### ISSUE THREAD

**Issue by NiklasTee** [Perevalov/qa_chatbots_exercises#11]
I managed to setup my NEL and Retriever component for the IR-based question answering in exercise 7. Unfortunately, I ran into some issues because the RoBERTa-For-QA input and output requirements are unknown. Maybe you could add some additional information in the exercise description regarding the following points:

1) What input type should the Retriever annotate so that the RoBERTa-For-QA component can retrieve and process it? 
String / List of Token / List of Strings (for multiple subtexts)?

2) BERT can only process 512 Tokens at a time. Will the tokenization be perfomed by the RoBERTa-For-QA  component? And is the cut-off done automatically or do we need to take care of this?

3) After the annotation is created by the RoBERTa-For-QA component, will it also return the answer to the General Chatbot frontend, or do we need to add another component here?

**Comment by Perevalov** [comment]
@NiklasTee 
1. The component uses the following query to get the passage from the Retriever:
```python
    SPARQLquery = """
        PREFIX dbr: <http://dbpedia.org/resource/>
        PREFIX dbo: <http://dbpedia.org/ontology/>
        PREFIX qa: <http://www.wdaqua.eu/qa#>
        PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
        PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
        PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
        
        SELECT ?passage
        FROM <{uuid}> 
        WHERE {{
            ?a rdf:type qa:AnnotationOfTextualPassage .
            ?a oa:hasBody ?passage .  
        }}
    """.format(uuid=triplestore_ingraph_uuid)
```
2. Currently, RoBERTa-For-QA just cuts the input to 512 tokens.
3. The general chatbot UI will automatically fetch the output. So, RoBERTa-For-QA should be the last component in the pipeline.

For the transparency I released the code for RoBERTa-For-QA at: https://github.com/Perevalov/qa_chatbots_exercises/tree/main/exercise_7/bert_for_qa

**Comment by NiklasTee** [comment]
Thank you for the answers and for the source code of RoBERTa-For-QA. 

I was able to figure out my mistake: 

The retriever must annotate the passage through the rdfs-label `qa:AnnotationOfTextualPassage`. I previously used `qa:AnnotationOfAnswerSPARQL` .
